### PR TITLE
incorrect path name fix

### PR DESCRIPTION
**Pull request by cdot65**
This simple misspelling causes the creation of AuthenticationProfile objects to fail

```
PanXapiError:  authentication-profile -> MyRADIUS -> locakout unexpected here
````

### CODE REVIEW

**Comment by cdot65** [comment]
Addresses #526

**Review by shinmog — APPROVED** [review]
lgtm

**Comment by shinmog** [comment]
The code is fine, but the CI is still failing on the docs task.  There's [another PR](https://github.com/PaloAltoNetworks/pan-os-python/pull/538) open for that.

**Comment by paulmnguyen** [comment]
The PR to fix the CI/CD was merged to develop. Please rebase develop into your branch and push it.

**Review by shinmog — APPROVED** [review]
lgtm

**Pull request merged**
