### PR TITLE
added new_appid to allowed parameters for ApplicationFilter. Need to …

### PR DESCRIPTION
**Pull request by keithcampbelljr**
## Description

Pep8 formattin
Added additional parameter for applicationfilter class to allow for "Apply to New App-IDs only"

## Motivation and Context

https://github.com/PaloAltoNetworks/pan-os-python/issues/522
https://github.com/PaloAltoNetworks/pan-os-python/issues/518

## How Has This Been Tested?

Tested against Panorama lab environment, verified filter created and had the correct "Apply to New App-IDs only" check box checked.

## Screenshots (if appropriate)

N/A

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [X ] I have updated the documentation accordingly.
- [X ] I have read the **CONTRIBUTING** document.
- [X ] I have added tests to cover my changes if appropriate.
- [X ] All new and existing tests passed.

### CODE REVIEW

**Comment by shinmog** [comment]
formatting needs to be addressed

**Comment by keithcampbelljr** [comment]
I think my VSC extension caused this. I’m going to abandon this and start fresh and ensure my linter doesn’t change stuff.

**Comment by keithcampbelljr** [comment]
@shinmog Hey! I managed to get formatting to pass. I have an extension 'auto pep8' which was causing the silly issue. Should be clear now :)

Might have another PR this evening for another issue.

**Review by shinmog — APPROVED** [review]
i think having an empty docstring is going to be a check that the CI needs to start doing, but i won't hold this PR up for that given that there is a param also in the class with an empty docstring.

**Pull request merged**
